config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'register_class/new'
  post 'register_class/create'
  get 'register_class/show'
  get 'race/new'
  get 'race/show'
  post 'race/createFeature'
  post 'race/createLanguage'
  post 'race/createProficiency'
  post 'race/createSkill'
  post 'auth' => "login#auth", as: "login_auth" 
  get 'login' => "login#login", as: "login"
  get 'logout' => "login#logout", as: "logout"
  get 'usuario/new'
  get 'usuario/show/:id' => "usuario#show", as: "usuario_show"
  post 'usuario/create'
  get 'sheet/new'
  post 'sheet/create'
  get 'sheet/home'
  get 'sheet/show/:id' => "sheet#show", as: "sheet_show"
  root "application#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/class_feature.rb
class ClassFeature < ApplicationRecord
end

app/models/feature.rb
class Feature < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/proficiency.rb
class Proficiency < ApplicationRecord
end

app/models/race.rb
class Race < ApplicationRecord
end

app/models/race_feature.rb
class RaceFeature < ApplicationRecord
  belongs_to :race
  belongs_to :feature
end

app/models/race_language.rb
class RaceLanguage < ApplicationRecord
  belongs_to :race
  belongs_to :language
end

app/models/race_proficiency.rb
class RaceProficiency < ApplicationRecord
  belongs_to :race
  belongs_to :proficiency
end

app/models/race_skill.rb
class RaceSkill < ApplicationRecord
  belongs_to :race
  belongs_to :skill
end

app/models/sheet.rb
class Sheet < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/models/tb_class.rb
class TbClass < ApplicationRecord
end

app/models/tb_class_feature.rb
class TbClassFeature < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_secure_password
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  include LoginHelper
  
  def auth
    @parametros = login_params
    @user = Usuario.find_by(email: @parametros[:email])
    if(@user && @user.authenticate(@parametros[:password]))
      log_in @user
      redirect_to usuario_show_path(@user)
    else
      redirect_to login_path
    end
  end

  def login
  end

  def logout
    log_out
    redirect_to root_path
  end
  
    private 
    def login_params
      params.require(:login).permit(:email, :password)
    end
end

app/controllers/race_controller.rb
class RaceController < ApplicationController
  def new
    @lang = Language.new
    @skill = Skill.new
    @prof = Proficiency.new
    @feature = Feature.new
  end

  def show
  end

  def createFeature
    @feature = Feature.new(feature_params)
    @feature.save
    @user = Usuario.first
    redirect_to usuario_show_path(@user)
  end

  def createLanguage
    @lang = Language.new(lang_params)
    @lang.save
    @user = Usuario.first
    redirect_to usuario_show_path(@user)
  end

  def createProficiency
    @prof = Proficiency.new(prof_params)
    @prof.save
         @user = Usuario.first
    redirect_to usuario_show_path(@user)
  end

  def createSkill
      @skill = Skill.new(skill_params)
      @skill.save
           @user = Usuario.first
    redirect_to usuario_show_path(@user)
  end
  
    private def feature_params
    params.require(:feature).permit(:name,:level,:desc)
  end
  private def prof_params
    params.require(:proficiency).permit(:name,:category,:desc)  
  end
  
  private def lang_params
    params.require(:language).permit(:name)
  end
  
  private def skill_params
    params.require(:skill).permit(:name,:attr)
  end
end

app/controllers/usuario_controller.rb
class UsuarioController < ApplicationController
  include LoginHelper
  
  def new
    @user = Usuario.new
  end

  def show
    @sheets = Sheet.all
    if(logged_in?)
      @user = Usuario.find(params[:id])
    else
      redirect_to root_path
    end
  end
  

  def create
    @user = Usuario.new(user_params)
    if @user.save 
      redirect_to usuario_show_path(@user)
    else
      render "new"
    end
  end
  
  private
    def user_params
      params.require(:usuario).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def log_out
        session.delete(:user_id)
    end
    
    def logged_in?
        !session[:user_id].nil?
    end
end

app/helpers/race_helper.rb
module RaceHelper
end

app/helpers/sheet_helper.rb
module SheetHelper
end

app/views/usuario/new.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
		<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		<title>Register</title>
	</head>
	<body>
	  <style>
	  </style>
	  <%= render 'layouts/header' %>
    <h1>Register</h1>
    <section>
        <%= form_for(@user, url: usuario_create_path) do |f| %>
        <div class="input txt">
          <%= f.label :name %>
          <%= f.text_field :name %>
        </div>
        <div class="input txt">
          <%= f.label :email %>
          <%= f.email_field :email %>
        </div>
        <div class="input">
          <%= f.label :password %>
          <%= f.password_field :password %>
        </div>
        <div class="input">
          <%= f.label :password_confirmation, "Confirmation" %>
          <%= f.password_field :password_confirmation %>
        </div>
        <div class="buttonduo">
          <%= f.submit "Create my account", class: "btnduo" %>
        </div>
        <div class="buttonduo">
          <%= button_to "Back", root_path, :method => "get", class: "btnduo" %>
        </div>
        <% end %>
    </section>
  </body>
</html>

app/views/usuario/show.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
		<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		<title>Home</title>
	</head>
    <body>
        <%= render 'layouts/header'%>
        <div class="menu" id="myMenu">
    		<%= link_to 'New...', race_new_path %>
    		<%= link_to 'New Sheet', sheet_new_path %>
    		<%= link_to 'Logout', logout_path %>
    		<a href="javascript:void(0);" class="icon" onclick="myFunction()">&#9776;</a>
	    </div>
        

        <div class="table">
            <%= render 'sheet/home' %>
        </div>
        <script>
    		/* Toggle between adding and removing the "responsive" class to menu when the user clicks on the icon */
    		function myFunction() {
    			var x = document.getElementById("myMenu");
    			if (x.className === "menu") {
    				x.className += " responsive";
    			} else {
    				x.className = "menu";
    			}
    		}
	    </script>
    </body>
</html>