config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'register_class/new'
  post 'register_class/create'
  get 'register_class/show'
  get 'race/new'
  get 'race/show'
  post 'race/createFeature'
  post 'race/createLanguage'
  post 'race/createProficiency'
  post 'race/createSkill'
  post 'auth' => "login#auth", as: "login_auth" 
  get 'login' => "login#login", as: "login"
  get 'logout' => "login#logout", as: "logout"
  get 'usuario/new'
  get 'usuario/show/:id' => "usuario#show", as: "usuario_show"
  post 'usuario/create'
  get 'sheet/new'
  post 'sheet/create'
  get 'sheet/home'
  get 'sheet/show/:id' => "sheet#show", as: "sheet_show"
  root "application#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/class_feature.rb
class ClassFeature < ApplicationRecord
end

app/models/feature.rb
class Feature < ApplicationRecord
end

app/models/language.rb
class Language < ApplicationRecord
end

app/models/proficiency.rb
class Proficiency < ApplicationRecord
end

app/models/race.rb
class Race < ApplicationRecord
end

app/models/race_feature.rb
class RaceFeature < ApplicationRecord
  belongs_to :race
  belongs_to :feature
end

app/models/race_language.rb
class RaceLanguage < ApplicationRecord
  belongs_to :race
  belongs_to :language
end

app/models/race_proficiency.rb
class RaceProficiency < ApplicationRecord
  belongs_to :race
  belongs_to :proficiency
end

app/models/race_skill.rb
class RaceSkill < ApplicationRecord
  belongs_to :race
  belongs_to :skill
end

app/models/sheet.rb
class Sheet < ApplicationRecord
end

app/models/skill.rb
class Skill < ApplicationRecord
end

app/models/tb_class.rb
class TbClass < ApplicationRecord
end

app/models/tb_class_feature.rb
class TbClassFeature < ApplicationRecord
end

app/models/usuario.rb
class Usuario < ApplicationRecord
  has_secure_password
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  include LoginHelper
  
  def auth
    @parametros = login_params
    @user = Usuario.find_by(email: @parametros[:email])
    if(@user && @user.authenticate(@parametros[:password]))
      log_in @user
      redirect_to usuario_show_path(@user)
    else
      redirect_to login_path
    end
  end

  def login
  end

  def logout
    log_out
    redirect_to root_path
  end
  
    private 
    def login_params
      params.require(:login).permit(:email, :password)
    end
end

app/controllers/race_controller.rb
class RaceController < ApplicationController
  def new
    @lang = Language.new
    @skill = Skill.new
    @prof = Proficiency.new
    @feature = Feature.new
  end

  def show
  end

  def createFeature
    @feature = Feature.new(feature_params)
    @feature.save
    @user = Usuario.first
    redirect_to usuario_show_path(@user)
  end

  def createLanguage
    @lang = Language.new(lang_params)
    @lang.save
    @user = Usuario.first
    redirect_to usuario_show_path(@user)
  end

  def createProficiency
    @prof = Proficiency.new(prof_params)
    @prof.save
         @user = Usuario.first
    redirect_to usuario_show_path(@user)
  end

  def createSkill
      @skill = Skill.new(skill_params)
      @skill.save
           @user = Usuario.first
    redirect_to usuario_show_path(@user)
  end
  
    private def feature_params
    params.require(:feature).permit(:name,:level,:desc)
  end
  private def prof_params
    params.require(:proficiency).permit(:name,:category,:desc)  
  end
  
  private def lang_params
    params.require(:language).permit(:name)
  end
  
  private def skill_params
    params.require(:skill).permit(:name,:attr)
  end
end

app/controllers/sheet_controller.rb
class SheetController < ApplicationController
   before_action :set_sheet, only: [:show, :edit, :update, :destroy]
   
   def set_sheet
     @setsheet = Sheet.find(params[:id])
   end
   
  def new
    @sheet = Sheet.new()
  end
  
  def create
    @user = Usuario.first
    @sheet = Sheet.new(sheet_params)
    @sheet.save!
    redirect_to usuario_show_path(@user)
  end

  
  
  def sheet_params
    params.require(:sheet).permit(:name,:race,:spec,:level,:str,:dex,:con,:int,:wis,:cha,:skill1,:skill2,:skill3,:skill4,:prof1,:prof2,:lang1,:lang2)
  end
  
  def show
    @skills = Skill.all
  end
  
  def home
    @sheets = Sheet.all
  end
  def show_params
      params.require(:sheet).permit(:id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/login_helper.rb
module LoginHelper
    def log_in(user)
        session[:user_id] = user.id
    end
    
    def log_out
        session.delete(:user_id)
    end
    
    def logged_in?
        !session[:user_id].nil?
    end
end

app/helpers/race_helper.rb
module RaceHelper
end

app/helpers/register_class_helper.rb
module RegisterClassHelper
end

app/helpers/sheet_helper.rb
module SheetHelper
end

app/views/race/createFeature.html.erb
<h1>Race#createFeature</h1>
<p>Find me in app/views/race/createFeature.html.erb</p>

app/views/race/createLanguage.html.erb
<h1>Race#createLanguage</h1>
<p>Find me in app/views/race/createLanguage.html.erb</p>

app/views/race/createProficiency.html.erb
<h1>Race#createProficiency</h1>
<p>Find me in app/views/race/createProficiency.html.erb</p>

app/views/race/createSkill.html.erb
<h1>Race#createSkill</h1>
<p>Find me in app/views/race/createSkill.html.erb</p>

app/views/race/new.html.erb
 <%= render 'layouts/header' %>
<div id="tabs" class="tabs">
	<nav>
		<ul>
			<li><a href="#section-1"><span>Language</span></a></li>
			<li><a href="#section-2"><span>Class Feature</span></a></li>
			<li><a href="#section-3"><span>Proficiency</span></a></li>
		</ul>
	</nav>
	<div class="content">
		<section id="section-1">
		    <%= form_for(@lang, url: race_createLanguage_path) do |f| %>
                  <div class="input txt" style="">
                    <%= f.label :name %>
                    <%= f.text_field :name%>
                  </div>
                  <div class="button">
                    <%= f.submit "New", class: "btn" %>
            </div><% end %>
		</section>
		<section id="section-2">
            <%= form_for(@feature, url: race_createFeature_path) do |f| %>
                <div class="input">
                    <%= f.label :name %>
                    <%= f.text_field :name %>
                </div>
                <div class="input">
                    <%= f.label :level %>
                    <%= f.text_field :level %>
                </div>
                <div class="input txt">
                    <%= f.label :desc %>
                    <%= f.text_field :desc%>
                </div>
                  <div class="button">
                    <%= f.submit "New", class: "btn" %>
            </div><% end %>
		</section>
		<section id="section-3">
            <%= form_for(@prof, url: race_createProficiency_path) do |f| %>
                  <div class="input">
                    <%= f.label :name %>
                    <%= f.text_field :name %>
                  </div>
                        <div class="input">
                    <%= f.label :category %>
                    <%= f.text_field :category %>
                  </div>
                <div class="input txt">
                    <%= f.label :desc %>
                    <%= f.text_field :desc%>
                </div>
                  <div class="button">
                    <%= f.submit "New", class: "btn" %>
            </div><% end %>
		</section>

	</div><!-- /content -->
</div><!-- /tabs -->
<script src="js/cbpFWTabs.js"></script>
<script>
	new CBPFWTabs( document.getElementById( 'tabs' ) );
</script>

app/views/race/show.html.erb
<h1>Race#show</h1>
<p>Find me in app/views/race/show.html.erb</p>

app/views/sheet/_home.html.erb
<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @sheets.each do |sheet| %>
      <tr>
        <td><%= sheet.id %></td>
        <td><%= sheet.name %></td>
        <td><%= link_to 'Show', sheet_show_path(sheet) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sheet/home.html.erb
<%= render 'layouts/header' %>
<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @sheets.each do |sheet| %>
      <tr>
        <td><%= sheet.id %></td>
        <td><%= sheet.name %></td>
        <td><%= link_to 'Show', sheet_show_path(sheet) %></td>
        <td><%= link_to 'Delete' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/sheet/new.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
		<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		<title>Register</title>
	</head>
	<body>
        <%= render 'layouts/header'%>
        <h1>New Sheet</h1>
        <%= form_for(@sheet, url: sheet_create_path) do |f| %>
        <div class="input">
            <%= f.label :name %>
            <%= f.text_field :name%>
        </div>
        <div class="input">
            <%= f.label :level%>
            <%= f.text_field :level%>
        </div>
        <div class="input">
            <%= f.label :race %>
            <%= f.select :race, options_from_collection_for_select(Race.all,:id,:name)%>
        </div>
        <div class="input">
            <%= f.label :class%>
            <%= f.select :spec, options_from_collection_for_select(TbClass.all,:id,:name)%>
        </div>
        <div class="input">
            <%= f.label :str %>
            <%= f.text_field :str%>
        </div>
        <div class="input">
            <%= f.label :dex %>
            <%= f.text_field :dex%>
        </div>
        <div class="input">
            <%= f.label :con%>
            <%= f.text_field :con%>
        </div>
        <div class="input">
            <%= f.label :int%>
            <%= f.text_field :int%>
        </div>
        <div class="input">
            <%= f.label :wis%>
            <%= f.text_field :wis%>
        </div>
        <div class="input">
            <%= f.label :cha%>
            <%= f.text_field :cha%>
        </div>
        <div class="input">
            <%= f.label :skill1 %>
            <%= f.select :skill1, options_from_collection_for_select(Skill.all,:id,:name)%>
        </div>
        <div class="input">
            <%= f.label :skill2 %>
            <%= f.select :skill2, options_from_collection_for_select(Skill.all,:id,:name)%>
        </div>
        <div class="input">
            <%= f.label :skill3 %>
            <%= f.select :skill3, options_from_collection_for_select(Skill.all,:id,:name)%>
        </div>
        <div class="input">
            <%= f.label :skill4 %>
            <%= f.select :skill4, options_from_collection_for_select(Skill.all,:id,:name)%>
        </div>
        <div class="input">
            <%= f.label :prof1 %>
            <%= f.select :prof1,options_from_collection_for_select(Proficiency.all,:id,:name)%>
        </div>
        <div class="input">
            <%= f.label :prof2 %>
            <%= f.select :prof2,options_from_collection_for_select(Proficiency.all,:id,:name)%>
        </div>
        <div class="input">
            <%= f.label :lang1%>
            <%= f.select :lang1,options_from_collection_for_select(Language.all,:id,:name)%>
        </div>
        <div class="input">
            <%= f.label :lang2%>
            <%= f.select :lang2,options_from_collection_for_select(Language.all,:id,:name)%>
        </div>
        <div class="button">
            <%= f.submit "Next", class: "btn" %>
        </div>
        <%end%>
    </body>
</html>

app/views/sheet/show.html.erb
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"> 
		<meta name="viewport" content="width=device-width, initial-scale=1.0"> 
		<title>Home</title>
		
		<style>
            tbody tr:nth-child(odd){
                background-color:#eb7a83;
                color:black;
            }
            
            @media screen and (max-width: 520px) {
                th, td {
            	  padding: 0.5%;
                }
            }
        </style>
	</head>
<body>
    <div class="table">
        <div class="sheetMiddle">
            <div class="nmChar"><%=@setsheet.name %>, the <%=Race.find_by(id: @setsheet.race.to_i).name %> <%=TbClass.find_by(id: @setsheet.spec.to_i).name %></h1></div>
            <div class="lvlChar">Level:<%=@setsheet.level %> </div> 
            <% @hitdice=TbClass.find_by(id: @setsheet.spec.to_i).hit_dice%>
            <div  class="hpChar">Hp: <% if @setsheet.level == 1 %>
                <%=@hitdice %>
                <%else%>
                <% @hitdice = @hitdice + ((@hitdice/2+1)*(@setsheet.level - 1))%>
                <%= @hitdice %>
                <%end%></div>
        </div>
        <br>
        <table>
            <thead>
                <tr>
                    <th></th>
                    <th>SKILLS</th>
                    <th></th>
                </tr>
                <tr>
                    <th>Proficiency</th>
                    <th>Name</th>
                    <th>Attribute</th>
                </tr>
            </thead>
          <tbody>
            <% @skills.each do |skills| %>
                <tr>
                    <td><%if @setsheet.skill1.to_i == skills.id || @setsheet.skill2.to_i == skills.id || @setsheet.skill3.to_i == skills.id || @setsheet.skill4.to_i == skills.id %>
                        yes
                        <% else %>
                        no
                        <% end %>
                    </td>
                    <td><%= skills.name %></td>
                    <td><%= skills.attr %></td>
                 </tr>
            <% end %>
          </tbody>
        </table>
        <br>
        <table>
            <thead>
                <tr>
                    <th>Attribute</th>
                    <th>Value</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>Strength</td>
                    <td><%= @vl_str = @setsheet.str + Race.find_by(id: @setsheet.race).str %></td>
                </tr>
                <tr>
                    <td>Dexterity</td>
                    <td><%= @vl_dex = @setsheet.dex + Race.find_by(id: @setsheet.race).dex %></td>
                </tr>
                <tr>
                    <td>Constitution</td>
                    <td><%= @vl_con = @setsheet.con + Race.find_by(id: @setsheet.race).con %></td>
                </tr>
                <tr>
                    <td>Intelligence</td>
                    <td><%= @vl_int = @setsheet.int + Race.find_by(id: @setsheet.race).int %></td>
                </tr>            
                <tr>
                    <td>Wisdom</td>
                    <td><%= @vl_wis = @setsheet.wis + Race.find_by(id: @setsheet.race).wis %></td>
                </tr>            
                <tr>
                    <td>Charisma</td>
                    <td><%= @vl_cha = @setsheet.cha + Race.find_by(id: @setsheet.race).cha %></td>
                </tr>
            </tbody>
        </table>
    </div>
</body>
</html>